#############################################################################
# Makefile for building: cassette
# Generated by qmake (3.0) (Qt 5.0.1) on: Fri May 24 10:53:25 2013
# Project:  cassette.pro
# Template: app
# Command: /Users/mehdi/qtbase_bb10/bin/qmake -spec blackberry-armv7le-qcc CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile cassette.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = qcc -Vgcc_ntoarmv7le
CXX           = qcc -Vgcc_ntoarmv7le
DEFINES       = -DQ_OS_BLACKBERRY -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -fstack-protector-strong -mcpu=cortex-a9 -Wno-psabi -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -fstack-protector-strong -mcpu=cortex-a9 -Wno-psabi -lang-c++ -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../qtbase_bb10/mkspecs/blackberry-armv7le-qcc -I. -Iqtquick2applicationviewer -I../../qtbase_bb10/include -I../../qtbase_bb10/include/QtQuick -I../../qtbase_bb10/include/QtMultimedia -I../../qtbase_bb10/include/QtQml -I../../qtbase_bb10/include/QtNetwork -I../../qtbase_bb10/include/QtGui -I../../qtbase_bb10/include/QtCore -I. -I../../bbndkGold/target_10_0_9_1673/qnx6/usr/include -I../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/freetype2
LINK          = qcc -Vgcc_ntoarmv7le
LFLAGS        = -lang-c++ -Wl,-rpath-link,/Users/mehdi/bbndkGold/target_10_0_9_1673/qnx6/armle-v7/lib -Wl,-rpath-link,/Users/mehdi/bbndkGold/target_10_0_9_1673/qnx6/armle-v7/usr/lib -Wl,-rpath,/Users/mehdi/qtbase_bb10/lib
LIBS          = $(SUBLIBS) -L/Users/mehdi/bbndkGold/target_10_0_9_1673/qnx6/armle-v7/lib -L/Users/mehdi/bbndkGold/target_10_0_9_1673/qnx6/armle-v7/usr/lib -L/Users/mehdi/qtbase_bb10//lib -lQt5Quick -L/Users/mehdi/qtdeclarative/lib -L/Users/mehdi/bbndk/target_10_0_9_1673/qnx6/armle-v7/lib -L/Users/mehdi/bbndk/target_10_0_9_1673/qnx6/armle-v7/usr/lib -lQt5Multimedia -lQt5Qml -lQt5Network -lsocket -lQt5Gui -lQt5Core -lm -lbps -lGLESv2 -lEGL 
AR            = ntoarmv7-ar cqs
RANLIB        = ntoarmv7-ranlib
QMAKE         = /Users/mehdi/qtbase_bb10/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = ntoarmv7-strip
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mediabackend.cpp \
		qtquick2applicationviewer/qtquick2applicationviewer.cpp moc_qtquick2applicationviewer.cpp \
		moc_mediabackend.cpp
OBJECTS       = main.o \
		mediabackend.o \
		qtquick2applicationviewer.o \
		moc_qtquick2applicationviewer.o \
		moc_mediabackend.o
DIST          = ../../qtbase_bb10/mkspecs/features/spec_pre.prf \
		../../qtbase_bb10/mkspecs/qconfig.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_bootstrap.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_concurrent.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_core.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_gui.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_multimedia.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_network.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_opengl.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_platformsupport.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_printsupport.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qml.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qmltest.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_quick.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_quickparticles.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_sql.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_testlib.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_v8.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_widgets.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_xml.pri \
		../../qtbase_bb10/mkspecs/features/qt_functions.prf \
		../../qtbase_bb10/mkspecs/features/qt_config.prf \
		../../qtbase_bb10/mkspecs/common/g++-base.conf \
		../../qtbase_bb10/mkspecs/common/g++-unix.conf \
		../../qtbase_bb10/mkspecs/common/shell-unix.conf \
		../../qtbase_bb10/mkspecs/common/unix.conf \
		../../qtbase_bb10/mkspecs/common/qcc-base.conf \
		../../qtbase_bb10/mkspecs/common/qcc-base-qnx.conf \
		../../qtbase_bb10/mkspecs/common/qcc-base-qnx-armv7le.conf \
		../../qtbase_bb10/mkspecs/blackberry-armv7le-qcc/qmake.conf \
		../../qtbase_bb10/mkspecs/features/spec_post.prf \
		../../qtbase_bb10/mkspecs/features/exclusive_builds.prf \
		../../qtbase_bb10/mkspecs/features/default_pre.prf \
		../../qtbase_bb10/mkspecs/features/unix/default_pre.prf \
		qtquick2applicationviewer/qtquick2applicationviewer.pri \
		../../qtbase_bb10/mkspecs/features/debug.prf \
		../../qtbase_bb10/mkspecs/features/default_post.prf \
		../../qtbase_bb10/mkspecs/features/shared.prf \
		../../qtbase_bb10/mkspecs/features/qml_debug.prf \
		../../qtbase_bb10/mkspecs/features/declarative_debug.prf \
		../../qtbase_bb10/mkspecs/features/warn_on.prf \
		../../qtbase_bb10/mkspecs/features/qt.prf \
		../../qtbase_bb10/mkspecs/features/resources.prf \
		../../qtbase_bb10/mkspecs/features/moc.prf \
		../../qtbase_bb10/mkspecs/features/unix/opengl.prf \
		../../qtbase_bb10/mkspecs/features/unix/thread.prf \
		../../qtbase_bb10/mkspecs/features/testcase_targets.prf \
		../../qtbase_bb10/mkspecs/features/exceptions.prf \
		../../qtbase_bb10/mkspecs/features/yacc.prf \
		../../qtbase_bb10/mkspecs/features/lex.prf \
		cassette.pro \
		cassette.pro
QMAKE_TARGET  = cassette
DESTDIR       = 
TARGET        = cassette


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cassette.pro ../../qtbase_bb10/mkspecs/blackberry-armv7le-qcc/qmake.conf ../../qtbase_bb10/mkspecs/features/spec_pre.prf \
		../../qtbase_bb10/mkspecs/qconfig.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_bootstrap.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_concurrent.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_core.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_gui.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_multimedia.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_network.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_opengl.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_platformsupport.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_printsupport.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qml.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qmltest.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_quick.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_quickparticles.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_sql.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_testlib.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_v8.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_widgets.pri \
		../../qtbase_bb10/mkspecs/modules/qt_lib_xml.pri \
		../../qtbase_bb10/mkspecs/features/qt_functions.prf \
		../../qtbase_bb10/mkspecs/features/qt_config.prf \
		../../qtbase_bb10/mkspecs/common/g++-base.conf \
		../../qtbase_bb10/mkspecs/common/g++-unix.conf \
		../../qtbase_bb10/mkspecs/common/shell-unix.conf \
		../../qtbase_bb10/mkspecs/common/unix.conf \
		../../qtbase_bb10/mkspecs/common/qcc-base.conf \
		../../qtbase_bb10/mkspecs/common/qcc-base-qnx.conf \
		../../qtbase_bb10/mkspecs/common/qcc-base-qnx-armv7le.conf \
		../../qtbase_bb10/mkspecs/blackberry-armv7le-qcc/qmake.conf \
		../../qtbase_bb10/mkspecs/features/spec_post.prf \
		../../qtbase_bb10/mkspecs/features/exclusive_builds.prf \
		../../qtbase_bb10/mkspecs/features/default_pre.prf \
		../../qtbase_bb10/mkspecs/features/unix/default_pre.prf \
		qtquick2applicationviewer/qtquick2applicationviewer.pri \
		../../qtbase_bb10/mkspecs/features/debug.prf \
		../../qtbase_bb10/mkspecs/features/default_post.prf \
		../../qtbase_bb10/mkspecs/features/shared.prf \
		../../qtbase_bb10/mkspecs/features/qml_debug.prf \
		../../qtbase_bb10/mkspecs/features/declarative_debug.prf \
		../../qtbase_bb10/mkspecs/features/warn_on.prf \
		../../qtbase_bb10/mkspecs/features/qt.prf \
		../../qtbase_bb10/mkspecs/features/resources.prf \
		../../qtbase_bb10/mkspecs/features/moc.prf \
		../../qtbase_bb10/mkspecs/features/unix/opengl.prf \
		../../qtbase_bb10/mkspecs/features/unix/thread.prf \
		../../qtbase_bb10/mkspecs/features/testcase_targets.prf \
		../../qtbase_bb10/mkspecs/features/exceptions.prf \
		../../qtbase_bb10/mkspecs/features/yacc.prf \
		../../qtbase_bb10/mkspecs/features/lex.prf \
		cassette.pro \
		/Users/mehdi/qtbase_bb10/lib/libQt5Quick.prl \
		/Users/mehdi/qtbase_bb10/lib/libQt5Qml.prl \
		/Users/mehdi/qtbase_bb10/lib/libQt5Network.prl \
		/Users/mehdi/qtbase_bb10/lib/libQt5Core.prl \
		/Users/mehdi/qtbase_bb10/lib/libQt5Gui.prl \
		/Users/mehdi/qtbase_bb10/lib/libQt5Multimedia.prl
	$(QMAKE) -spec blackberry-armv7le-qcc CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile cassette.pro
../../qtbase_bb10/mkspecs/features/spec_pre.prf:
../../qtbase_bb10/mkspecs/qconfig.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_bootstrap.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_concurrent.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_core.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_gui.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_multimedia.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_network.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_opengl.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_platformsupport.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_printsupport.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_qml.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_qmldevtools.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_qmltest.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_quick.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_quickparticles.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_sql.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_testlib.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_v8.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_widgets.pri:
../../qtbase_bb10/mkspecs/modules/qt_lib_xml.pri:
../../qtbase_bb10/mkspecs/features/qt_functions.prf:
../../qtbase_bb10/mkspecs/features/qt_config.prf:
../../qtbase_bb10/mkspecs/common/g++-base.conf:
../../qtbase_bb10/mkspecs/common/g++-unix.conf:
../../qtbase_bb10/mkspecs/common/shell-unix.conf:
../../qtbase_bb10/mkspecs/common/unix.conf:
../../qtbase_bb10/mkspecs/common/qcc-base.conf:
../../qtbase_bb10/mkspecs/common/qcc-base-qnx.conf:
../../qtbase_bb10/mkspecs/common/qcc-base-qnx-armv7le.conf:
../../qtbase_bb10/mkspecs/blackberry-armv7le-qcc/qmake.conf:
../../qtbase_bb10/mkspecs/features/spec_post.prf:
../../qtbase_bb10/mkspecs/features/exclusive_builds.prf:
../../qtbase_bb10/mkspecs/features/default_pre.prf:
../../qtbase_bb10/mkspecs/features/unix/default_pre.prf:
qtquick2applicationviewer/qtquick2applicationviewer.pri:
../../qtbase_bb10/mkspecs/features/debug.prf:
../../qtbase_bb10/mkspecs/features/default_post.prf:
../../qtbase_bb10/mkspecs/features/shared.prf:
../../qtbase_bb10/mkspecs/features/qml_debug.prf:
../../qtbase_bb10/mkspecs/features/declarative_debug.prf:
../../qtbase_bb10/mkspecs/features/warn_on.prf:
../../qtbase_bb10/mkspecs/features/qt.prf:
../../qtbase_bb10/mkspecs/features/resources.prf:
../../qtbase_bb10/mkspecs/features/moc.prf:
../../qtbase_bb10/mkspecs/features/unix/opengl.prf:
../../qtbase_bb10/mkspecs/features/unix/thread.prf:
../../qtbase_bb10/mkspecs/features/testcase_targets.prf:
../../qtbase_bb10/mkspecs/features/exceptions.prf:
../../qtbase_bb10/mkspecs/features/yacc.prf:
../../qtbase_bb10/mkspecs/features/lex.prf:
cassette.pro:
/Users/mehdi/qtbase_bb10/lib/libQt5Quick.prl:
/Users/mehdi/qtbase_bb10/lib/libQt5Qml.prl:
/Users/mehdi/qtbase_bb10/lib/libQt5Network.prl:
/Users/mehdi/qtbase_bb10/lib/libQt5Core.prl:
/Users/mehdi/qtbase_bb10/lib/libQt5Gui.prl:
/Users/mehdi/qtbase_bb10/lib/libQt5Multimedia.prl:
qmake: FORCE
	@$(QMAKE) -spec blackberry-armv7le-qcc CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile cassette.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/cassette1.0.0 || $(MKDIR) .tmp/cassette1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cassette1.0.0/ && $(COPY_FILE) --parents qtquick2applicationviewer/qtquick2applicationviewer.h mediabackend.h .tmp/cassette1.0.0/ && $(COPY_FILE) --parents main.cpp mediabackend.cpp qtquick2applicationviewer/qtquick2applicationviewer.cpp .tmp/cassette1.0.0/ && (cd `dirname .tmp/cassette1.0.0` && $(TAR) cassette1.0.0.tar cassette1.0.0 && $(COMPRESS) cassette1.0.0.tar) && $(MOVE) `dirname .tmp/cassette1.0.0`/cassette1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cassette1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_qtquick2applicationviewer.cpp moc_mediabackend.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtquick2applicationviewer.cpp moc_mediabackend.cpp
moc_qtquick2applicationviewer.cpp: ../../qtbase_bb10/include/QtQuick/QQuickView \
		../../qtbase_bb10/include/QtQuick/qquickview.h \
		../../qtbase_bb10/include/QtQuick/qquickwindow.h \
		../../qtbase_bb10/include/QtQuick/qtquickglobal.h \
		../../qtbase_bb10/include/QtCore/qglobal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stddef.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/srcversion.h \
		../../qtbase_bb10/include/QtCore/qconfig.h \
		../../qtbase_bb10/include/QtCore/qfeatures.h \
		../../qtbase_bb10/include/QtCore/qsystemdetection.h \
		../../qtbase_bb10/include/QtCore/qcompilerdetection.h \
		../../qtbase_bb10/include/QtCore/qprocessordetection.h \
		../../qtbase_bb10/include/QtCore/qlogging.h \
		../../qtbase_bb10/include/QtCore/qflags.h \
		../../qtbase_bb10/include/QtCore/qtypeinfo.h \
		../../qtbase_bb10/include/QtCore/qtypetraits.h \
		../../qtbase_bb10/include/QtCore/qsysinfo.h \
		../../qtbase_bb10/include/QtCore/qmetatype.h \
		../../qtbase_bb10/include/QtCore/qatomic.h \
		../../qtbase_bb10/include/QtCore/qbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_bootstrap.h \
		../../qtbase_bb10/include/QtCore/qgenericatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_msvc.h \
		../../qtbase_bb10/include/QtCore/qatomic_integrity.h \
		../../qtbase_bb10/include/QtCore/qoldbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_vxworks.h \
		../../qtbase_bb10/include/QtCore/qatomic_power.h \
		../../qtbase_bb10/include/QtCore/qatomic_alpha.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv7.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv6.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv5.h \
		../../qtbase_bb10/include/QtCore/qatomic_bfin.h \
		../../qtbase_bb10/include/QtCore/qatomic_ia64.h \
		../../qtbase_bb10/include/QtCore/qatomic_mips.h \
		../../qtbase_bb10/include/QtCore/qatomic_s390.h \
		../../qtbase_bb10/include/QtCore/qatomic_sh4a.h \
		../../qtbase_bb10/include/QtCore/qatomic_sparc.h \
		../../qtbase_bb10/include/QtCore/qatomic_x86.h \
		../../qtbase_bb10/include/QtCore/qatomic_cxx11.h \
		../../qtbase_bb10/include/QtCore/qatomic_gcc.h \
		../../qtbase_bb10/include/QtCore/qatomic_unix.h \
		../../qtbase_bb10/include/QtCore/qbytearray.h \
		../../qtbase_bb10/include/QtCore/qrefcount.h \
		../../qtbase_bb10/include/QtCore/qnamespace.h \
		../../qtbase_bb10/include/QtCore/qarraydata.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/strings.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/x86/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string_chk.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdlib.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/malloc.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_pack64.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/alloca.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_packpop.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/wait.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/signal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/siginfo.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdarg.h \
		../../qtbase_bb10/include/QtCore/qstring.h \
		../../qtbase_bb10/include/QtCore/qchar.h \
		../../qtbase_bb10/include/QtCore/qstringbuilder.h \
		../../qtbase_bb10/include/QtCore/qvarlengtharray.h \
		../../qtbase_bb10/include/QtCore/qcontainerfwd.h \
		../../qtbase_bb10/include/QtCore/qalgorithms.h \
		../../qtbase_bb10/include/QtCore/qisenum.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs_impl.h \
		../../qtbase_bb10/include/QtGui/qopengl.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/GLES2/gl2.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/GLES2/gl2platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/KHR/khrplatform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdint.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/inttypes.h \
		../../qtbase_bb10/include/QtGui/qopengles2ext.h \
		../../qtbase_bb10/include/QtCore/qt_windows.h \
		../../qtbase_bb10/include/QtGui/qopenglext.h \
		../../qtbase_bb10/include/QtGui/qwindow.h \
		../../qtbase_bb10/include/QtCore/QObject \
		../../qtbase_bb10/include/QtCore/qobject.h \
		../../qtbase_bb10/include/QtCore/qlist.h \
		../../qtbase_bb10/include/QtCore/qiterator.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/limits.h \
		../../qtbase_bb10/include/QtCore/qcoreevent.h \
		../../qtbase_bb10/include/QtCore/qscopedpointer.h \
		../../qtbase_bb10/include/QtCore/qobject_impl.h \
		../../qtbase_bb10/include/QtCore/QEvent \
		../../qtbase_bb10/include/QtCore/QMargins \
		../../qtbase_bb10/include/QtCore/qmargins.h \
		../../qtbase_bb10/include/QtCore/QRect \
		../../qtbase_bb10/include/QtCore/qrect.h \
		../../qtbase_bb10/include/QtCore/qsize.h \
		../../qtbase_bb10/include/QtCore/qpoint.h \
		../../qtbase_bb10/include/QtGui/qsurface.h \
		../../qtbase_bb10/include/QtGui/qsurfaceformat.h \
		../../qtbase_bb10/include/QtGui/qwindowdefs.h \
		../../qtbase_bb10/include/QtGui/qwindowdefs_win.h \
		../../qtbase_bb10/include/QtGui/qicon.h \
		../../qtbase_bb10/include/QtGui/qpixmap.h \
		../../qtbase_bb10/include/QtGui/qpaintdevice.h \
		../../qtbase_bb10/include/QtGui/qcolor.h \
		../../qtbase_bb10/include/QtGui/qrgb.h \
		../../qtbase_bb10/include/QtCore/qstringlist.h \
		../../qtbase_bb10/include/QtCore/qdatastream.h \
		../../qtbase_bb10/include/QtCore/qiodevice.h \
		../../qtbase_bb10/include/QtCore/qpair.h \
		../../qtbase_bb10/include/QtCore/qregexp.h \
		../../qtbase_bb10/include/QtCore/qstringmatcher.h \
		../../qtbase_bb10/include/QtCore/qsharedpointer.h \
		../../qtbase_bb10/include/QtCore/qshareddata.h \
		../../qtbase_bb10/include/QtCore/qsharedpointer_impl.h \
		../../qtbase_bb10/include/QtCore/qhash.h \
		../../qtbase_bb10/include/QtGui/qimage.h \
		../../qtbase_bb10/include/QtGui/qtransform.h \
		../../qtbase_bb10/include/QtGui/qmatrix.h \
		../../qtbase_bb10/include/QtGui/qpolygon.h \
		../../qtbase_bb10/include/QtCore/qvector.h \
		../../qtbase_bb10/include/QtGui/qregion.h \
		../../qtbase_bb10/include/QtCore/qline.h \
		../../qtbase_bb10/include/QtGui/qpainterpath.h \
		../../qtbase_bb10/include/QtGui/qcursor.h \
		../../qtbase_bb10/include/QtGui/qevent.h \
		../../qtbase_bb10/include/QtGui/qkeysequence.h \
		../../qtbase_bb10/include/QtCore/qvariant.h \
		../../qtbase_bb10/include/QtCore/qmap.h \
		../../qtbase_bb10/include/QtCore/qdebug.h \
		../../qtbase_bb10/include/QtCore/qtextstream.h \
		../../qtbase_bb10/include/QtCore/qlocale.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio_chk.h \
		../../qtbase_bb10/include/QtCore/qset.h \
		../../qtbase_bb10/include/QtCore/qcontiguouscache.h \
		../../qtbase_bb10/include/QtCore/qurl.h \
		../../qtbase_bb10/include/QtCore/qurlquery.h \
		../../qtbase_bb10/include/QtCore/qfile.h \
		../../qtbase_bb10/include/QtCore/qfiledevice.h \
		../../qtbase_bb10/include/QtGui/qvector2d.h \
		../../qtbase_bb10/include/QtGui/qtouchdevice.h \
		../../qtbase_bb10/include/QtQml/qqmldebug.h \
		../../qtbase_bb10/include/QtQml/qtqmlglobal.h \
		qtquick2applicationviewer/qtquick2applicationviewer.h
	/Users/mehdi/qtbase_bb10//bin/moc $(DEFINES) $(INCPATH) -D__QNXNTO__ qtquick2applicationviewer/qtquick2applicationviewer.h -o moc_qtquick2applicationviewer.cpp

moc_mediabackend.cpp: ../../qtbase_bb10/include/QtCore/QObject \
		../../qtbase_bb10/include/QtCore/qobject.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs.h \
		../../qtbase_bb10/include/QtCore/qnamespace.h \
		../../qtbase_bb10/include/QtCore/qglobal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stddef.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/srcversion.h \
		../../qtbase_bb10/include/QtCore/qconfig.h \
		../../qtbase_bb10/include/QtCore/qfeatures.h \
		../../qtbase_bb10/include/QtCore/qsystemdetection.h \
		../../qtbase_bb10/include/QtCore/qcompilerdetection.h \
		../../qtbase_bb10/include/QtCore/qprocessordetection.h \
		../../qtbase_bb10/include/QtCore/qlogging.h \
		../../qtbase_bb10/include/QtCore/qflags.h \
		../../qtbase_bb10/include/QtCore/qtypeinfo.h \
		../../qtbase_bb10/include/QtCore/qtypetraits.h \
		../../qtbase_bb10/include/QtCore/qsysinfo.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs_impl.h \
		../../qtbase_bb10/include/QtCore/qstring.h \
		../../qtbase_bb10/include/QtCore/qchar.h \
		../../qtbase_bb10/include/QtCore/qbytearray.h \
		../../qtbase_bb10/include/QtCore/qrefcount.h \
		../../qtbase_bb10/include/QtCore/qatomic.h \
		../../qtbase_bb10/include/QtCore/qbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_bootstrap.h \
		../../qtbase_bb10/include/QtCore/qgenericatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_msvc.h \
		../../qtbase_bb10/include/QtCore/qatomic_integrity.h \
		../../qtbase_bb10/include/QtCore/qoldbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_vxworks.h \
		../../qtbase_bb10/include/QtCore/qatomic_power.h \
		../../qtbase_bb10/include/QtCore/qatomic_alpha.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv7.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv6.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv5.h \
		../../qtbase_bb10/include/QtCore/qatomic_bfin.h \
		../../qtbase_bb10/include/QtCore/qatomic_ia64.h \
		../../qtbase_bb10/include/QtCore/qatomic_mips.h \
		../../qtbase_bb10/include/QtCore/qatomic_s390.h \
		../../qtbase_bb10/include/QtCore/qatomic_sh4a.h \
		../../qtbase_bb10/include/QtCore/qatomic_sparc.h \
		../../qtbase_bb10/include/QtCore/qatomic_x86.h \
		../../qtbase_bb10/include/QtCore/qatomic_cxx11.h \
		../../qtbase_bb10/include/QtCore/qatomic_gcc.h \
		../../qtbase_bb10/include/QtCore/qatomic_unix.h \
		../../qtbase_bb10/include/QtCore/qarraydata.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/strings.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/x86/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string_chk.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdlib.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/malloc.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_pack64.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/alloca.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_packpop.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/wait.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/signal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/siginfo.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdarg.h \
		../../qtbase_bb10/include/QtCore/qstringbuilder.h \
		../../qtbase_bb10/include/QtCore/qlist.h \
		../../qtbase_bb10/include/QtCore/qalgorithms.h \
		../../qtbase_bb10/include/QtCore/qiterator.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/limits.h \
		../../qtbase_bb10/include/QtCore/qcoreevent.h \
		../../qtbase_bb10/include/QtCore/qscopedpointer.h \
		../../qtbase_bb10/include/QtCore/qmetatype.h \
		../../qtbase_bb10/include/QtCore/qvarlengtharray.h \
		../../qtbase_bb10/include/QtCore/qcontainerfwd.h \
		../../qtbase_bb10/include/QtCore/qisenum.h \
		../../qtbase_bb10/include/QtCore/qobject_impl.h \
		../../qtbase_bb10/include/QtCore/QStringList \
		../../qtbase_bb10/include/QtCore/qstringlist.h \
		../../qtbase_bb10/include/QtCore/qdatastream.h \
		../../qtbase_bb10/include/QtCore/qiodevice.h \
		../../qtbase_bb10/include/QtCore/qpair.h \
		../../qtbase_bb10/include/QtCore/qregexp.h \
		../../qtbase_bb10/include/QtCore/qstringmatcher.h \
		mediabackend.h
	/Users/mehdi/qtbase_bb10//bin/moc $(DEFINES) $(INCPATH) -D__QNXNTO__ mediabackend.h -o moc_mediabackend.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../qtbase_bb10/include/QtGui/QGuiApplication \
		../../qtbase_bb10/include/QtGui/qguiapplication.h \
		../../qtbase_bb10/include/QtCore/qcoreapplication.h \
		../../qtbase_bb10/include/QtCore/qobject.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs.h \
		../../qtbase_bb10/include/QtCore/qnamespace.h \
		../../qtbase_bb10/include/QtCore/qglobal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stddef.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/srcversion.h \
		../../qtbase_bb10/include/QtCore/qconfig.h \
		../../qtbase_bb10/include/QtCore/qfeatures.h \
		../../qtbase_bb10/include/QtCore/qsystemdetection.h \
		../../qtbase_bb10/include/QtCore/qcompilerdetection.h \
		../../qtbase_bb10/include/QtCore/qprocessordetection.h \
		../../qtbase_bb10/include/QtCore/qlogging.h \
		../../qtbase_bb10/include/QtCore/qflags.h \
		../../qtbase_bb10/include/QtCore/qtypeinfo.h \
		../../qtbase_bb10/include/QtCore/qtypetraits.h \
		../../qtbase_bb10/include/QtCore/qsysinfo.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs_impl.h \
		../../qtbase_bb10/include/QtCore/qstring.h \
		../../qtbase_bb10/include/QtCore/qchar.h \
		../../qtbase_bb10/include/QtCore/qbytearray.h \
		../../qtbase_bb10/include/QtCore/qrefcount.h \
		../../qtbase_bb10/include/QtCore/qatomic.h \
		../../qtbase_bb10/include/QtCore/qbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_bootstrap.h \
		../../qtbase_bb10/include/QtCore/qgenericatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_msvc.h \
		../../qtbase_bb10/include/QtCore/qatomic_integrity.h \
		../../qtbase_bb10/include/QtCore/qoldbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_vxworks.h \
		../../qtbase_bb10/include/QtCore/qatomic_power.h \
		../../qtbase_bb10/include/QtCore/qatomic_alpha.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv7.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv6.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv5.h \
		../../qtbase_bb10/include/QtCore/qatomic_bfin.h \
		../../qtbase_bb10/include/QtCore/qatomic_ia64.h \
		../../qtbase_bb10/include/QtCore/qatomic_mips.h \
		../../qtbase_bb10/include/QtCore/qatomic_s390.h \
		../../qtbase_bb10/include/QtCore/qatomic_sh4a.h \
		../../qtbase_bb10/include/QtCore/qatomic_sparc.h \
		../../qtbase_bb10/include/QtCore/qatomic_x86.h \
		../../qtbase_bb10/include/QtCore/qatomic_cxx11.h \
		../../qtbase_bb10/include/QtCore/qatomic_gcc.h \
		../../qtbase_bb10/include/QtCore/qatomic_unix.h \
		../../qtbase_bb10/include/QtCore/qarraydata.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/strings.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/x86/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string_chk.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdlib.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/malloc.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_pack64.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/alloca.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_packpop.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/wait.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/signal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/siginfo.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdarg.h \
		../../qtbase_bb10/include/QtCore/qstringbuilder.h \
		../../qtbase_bb10/include/QtCore/qlist.h \
		../../qtbase_bb10/include/QtCore/qalgorithms.h \
		../../qtbase_bb10/include/QtCore/qiterator.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/limits.h \
		../../qtbase_bb10/include/QtCore/qcoreevent.h \
		../../qtbase_bb10/include/QtCore/qscopedpointer.h \
		../../qtbase_bb10/include/QtCore/qmetatype.h \
		../../qtbase_bb10/include/QtCore/qvarlengtharray.h \
		../../qtbase_bb10/include/QtCore/qcontainerfwd.h \
		../../qtbase_bb10/include/QtCore/qisenum.h \
		../../qtbase_bb10/include/QtCore/qobject_impl.h \
		../../qtbase_bb10/include/QtCore/qeventloop.h \
		../../qtbase_bb10/include/QtGui/qwindowdefs.h \
		../../qtbase_bb10/include/QtGui/qwindowdefs_win.h \
		../../qtbase_bb10/include/QtGui/qinputmethod.h \
		../../qtbase_bb10/include/QtCore/qlocale.h \
		../../qtbase_bb10/include/QtCore/qvariant.h \
		../../qtbase_bb10/include/QtCore/qmap.h \
		../../qtbase_bb10/include/QtCore/qpair.h \
		../../qtbase_bb10/include/QtCore/qdebug.h \
		../../qtbase_bb10/include/QtCore/qhash.h \
		../../qtbase_bb10/include/QtCore/qtextstream.h \
		../../qtbase_bb10/include/QtCore/qiodevice.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio_chk.h \
		../../qtbase_bb10/include/QtCore/qvector.h \
		../../qtbase_bb10/include/QtCore/qpoint.h \
		../../qtbase_bb10/include/QtCore/qset.h \
		../../qtbase_bb10/include/QtCore/qcontiguouscache.h \
		../../qtbase_bb10/include/QtCore/qshareddata.h \
		../../qtbase_bb10/include/QtCore/qsize.h \
		../../qtbase_bb10/include/QtQml/QQmlContext \
		../../qtbase_bb10/include/QtQml/qqmlcontext.h \
		../../qtbase_bb10/include/QtCore/qurl.h \
		../../qtbase_bb10/include/QtCore/qurlquery.h \
		../../qtbase_bb10/include/QtCore/qstringlist.h \
		../../qtbase_bb10/include/QtCore/qdatastream.h \
		../../qtbase_bb10/include/QtCore/qregexp.h \
		../../qtbase_bb10/include/QtCore/qstringmatcher.h \
		../../qtbase_bb10/include/QtQml/qjsvalue.h \
		../../qtbase_bb10/include/QtQml/qtqmlglobal.h \
		../../qtbase_bb10/include/QtCore/qsharedpointer.h \
		../../qtbase_bb10/include/QtCore/qsharedpointer_impl.h \
		qtquick2applicationviewer/qtquick2applicationviewer.h \
		../../qtbase_bb10/include/QtQuick/QQuickView \
		../../qtbase_bb10/include/QtQuick/qquickview.h \
		../../qtbase_bb10/include/QtQuick/qquickwindow.h \
		../../qtbase_bb10/include/QtQuick/qtquickglobal.h \
		../../qtbase_bb10/include/QtGui/qopengl.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/GLES2/gl2.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/GLES2/gl2platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/KHR/khrplatform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdint.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/inttypes.h \
		../../qtbase_bb10/include/QtGui/qopengles2ext.h \
		../../qtbase_bb10/include/QtCore/qt_windows.h \
		../../qtbase_bb10/include/QtGui/qopenglext.h \
		../../qtbase_bb10/include/QtGui/qwindow.h \
		../../qtbase_bb10/include/QtCore/QObject \
		../../qtbase_bb10/include/QtCore/QEvent \
		../../qtbase_bb10/include/QtCore/QMargins \
		../../qtbase_bb10/include/QtCore/qmargins.h \
		../../qtbase_bb10/include/QtCore/QRect \
		../../qtbase_bb10/include/QtCore/qrect.h \
		../../qtbase_bb10/include/QtGui/qsurface.h \
		../../qtbase_bb10/include/QtGui/qsurfaceformat.h \
		../../qtbase_bb10/include/QtGui/qicon.h \
		../../qtbase_bb10/include/QtGui/qpixmap.h \
		../../qtbase_bb10/include/QtGui/qpaintdevice.h \
		../../qtbase_bb10/include/QtGui/qcolor.h \
		../../qtbase_bb10/include/QtGui/qrgb.h \
		../../qtbase_bb10/include/QtGui/qimage.h \
		../../qtbase_bb10/include/QtGui/qtransform.h \
		../../qtbase_bb10/include/QtGui/qmatrix.h \
		../../qtbase_bb10/include/QtGui/qpolygon.h \
		../../qtbase_bb10/include/QtGui/qregion.h \
		../../qtbase_bb10/include/QtCore/qline.h \
		../../qtbase_bb10/include/QtGui/qpainterpath.h \
		../../qtbase_bb10/include/QtGui/qcursor.h \
		../../qtbase_bb10/include/QtGui/qevent.h \
		../../qtbase_bb10/include/QtGui/qkeysequence.h \
		../../qtbase_bb10/include/QtCore/qfile.h \
		../../qtbase_bb10/include/QtCore/qfiledevice.h \
		../../qtbase_bb10/include/QtGui/qvector2d.h \
		../../qtbase_bb10/include/QtGui/qtouchdevice.h \
		../../qtbase_bb10/include/QtQml/qqmldebug.h \
		mediabackend.h \
		../../qtbase_bb10/include/QtCore/QStringList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mediabackend.o: mediabackend.cpp mediabackend.h \
		../../qtbase_bb10/include/QtCore/QObject \
		../../qtbase_bb10/include/QtCore/qobject.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs.h \
		../../qtbase_bb10/include/QtCore/qnamespace.h \
		../../qtbase_bb10/include/QtCore/qglobal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stddef.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/srcversion.h \
		../../qtbase_bb10/include/QtCore/qconfig.h \
		../../qtbase_bb10/include/QtCore/qfeatures.h \
		../../qtbase_bb10/include/QtCore/qsystemdetection.h \
		../../qtbase_bb10/include/QtCore/qcompilerdetection.h \
		../../qtbase_bb10/include/QtCore/qprocessordetection.h \
		../../qtbase_bb10/include/QtCore/qlogging.h \
		../../qtbase_bb10/include/QtCore/qflags.h \
		../../qtbase_bb10/include/QtCore/qtypeinfo.h \
		../../qtbase_bb10/include/QtCore/qtypetraits.h \
		../../qtbase_bb10/include/QtCore/qsysinfo.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs_impl.h \
		../../qtbase_bb10/include/QtCore/qstring.h \
		../../qtbase_bb10/include/QtCore/qchar.h \
		../../qtbase_bb10/include/QtCore/qbytearray.h \
		../../qtbase_bb10/include/QtCore/qrefcount.h \
		../../qtbase_bb10/include/QtCore/qatomic.h \
		../../qtbase_bb10/include/QtCore/qbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_bootstrap.h \
		../../qtbase_bb10/include/QtCore/qgenericatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_msvc.h \
		../../qtbase_bb10/include/QtCore/qatomic_integrity.h \
		../../qtbase_bb10/include/QtCore/qoldbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_vxworks.h \
		../../qtbase_bb10/include/QtCore/qatomic_power.h \
		../../qtbase_bb10/include/QtCore/qatomic_alpha.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv7.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv6.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv5.h \
		../../qtbase_bb10/include/QtCore/qatomic_bfin.h \
		../../qtbase_bb10/include/QtCore/qatomic_ia64.h \
		../../qtbase_bb10/include/QtCore/qatomic_mips.h \
		../../qtbase_bb10/include/QtCore/qatomic_s390.h \
		../../qtbase_bb10/include/QtCore/qatomic_sh4a.h \
		../../qtbase_bb10/include/QtCore/qatomic_sparc.h \
		../../qtbase_bb10/include/QtCore/qatomic_x86.h \
		../../qtbase_bb10/include/QtCore/qatomic_cxx11.h \
		../../qtbase_bb10/include/QtCore/qatomic_gcc.h \
		../../qtbase_bb10/include/QtCore/qatomic_unix.h \
		../../qtbase_bb10/include/QtCore/qarraydata.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/strings.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/x86/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string_chk.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdlib.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/malloc.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_pack64.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/alloca.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_packpop.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/wait.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/signal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/siginfo.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdarg.h \
		../../qtbase_bb10/include/QtCore/qstringbuilder.h \
		../../qtbase_bb10/include/QtCore/qlist.h \
		../../qtbase_bb10/include/QtCore/qalgorithms.h \
		../../qtbase_bb10/include/QtCore/qiterator.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/limits.h \
		../../qtbase_bb10/include/QtCore/qcoreevent.h \
		../../qtbase_bb10/include/QtCore/qscopedpointer.h \
		../../qtbase_bb10/include/QtCore/qmetatype.h \
		../../qtbase_bb10/include/QtCore/qvarlengtharray.h \
		../../qtbase_bb10/include/QtCore/qcontainerfwd.h \
		../../qtbase_bb10/include/QtCore/qisenum.h \
		../../qtbase_bb10/include/QtCore/qobject_impl.h \
		../../qtbase_bb10/include/QtCore/QStringList \
		../../qtbase_bb10/include/QtCore/qstringlist.h \
		../../qtbase_bb10/include/QtCore/qdatastream.h \
		../../qtbase_bb10/include/QtCore/qiodevice.h \
		../../qtbase_bb10/include/QtCore/qpair.h \
		../../qtbase_bb10/include/QtCore/qregexp.h \
		../../qtbase_bb10/include/QtCore/qstringmatcher.h \
		../../qtbase_bb10/include/QtCore/QDirIterator \
		../../qtbase_bb10/include/QtCore/qdiriterator.h \
		../../qtbase_bb10/include/QtCore/qdir.h \
		../../qtbase_bb10/include/QtCore/qfileinfo.h \
		../../qtbase_bb10/include/QtCore/qfile.h \
		../../qtbase_bb10/include/QtCore/qfiledevice.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio_chk.h \
		../../qtbase_bb10/include/QtCore/qshareddata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mediabackend.o mediabackend.cpp

qtquick2applicationviewer.o: qtquick2applicationviewer/qtquick2applicationviewer.cpp qtquick2applicationviewer/qtquick2applicationviewer.h \
		../../qtbase_bb10/include/QtQuick/QQuickView \
		../../qtbase_bb10/include/QtQuick/qquickview.h \
		../../qtbase_bb10/include/QtQuick/qquickwindow.h \
		../../qtbase_bb10/include/QtQuick/qtquickglobal.h \
		../../qtbase_bb10/include/QtCore/qglobal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stddef.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/srcversion.h \
		../../qtbase_bb10/include/QtCore/qconfig.h \
		../../qtbase_bb10/include/QtCore/qfeatures.h \
		../../qtbase_bb10/include/QtCore/qsystemdetection.h \
		../../qtbase_bb10/include/QtCore/qcompilerdetection.h \
		../../qtbase_bb10/include/QtCore/qprocessordetection.h \
		../../qtbase_bb10/include/QtCore/qlogging.h \
		../../qtbase_bb10/include/QtCore/qflags.h \
		../../qtbase_bb10/include/QtCore/qtypeinfo.h \
		../../qtbase_bb10/include/QtCore/qtypetraits.h \
		../../qtbase_bb10/include/QtCore/qsysinfo.h \
		../../qtbase_bb10/include/QtCore/qmetatype.h \
		../../qtbase_bb10/include/QtCore/qatomic.h \
		../../qtbase_bb10/include/QtCore/qbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_bootstrap.h \
		../../qtbase_bb10/include/QtCore/qgenericatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_msvc.h \
		../../qtbase_bb10/include/QtCore/qatomic_integrity.h \
		../../qtbase_bb10/include/QtCore/qoldbasicatomic.h \
		../../qtbase_bb10/include/QtCore/qatomic_vxworks.h \
		../../qtbase_bb10/include/QtCore/qatomic_power.h \
		../../qtbase_bb10/include/QtCore/qatomic_alpha.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv7.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv6.h \
		../../qtbase_bb10/include/QtCore/qatomic_armv5.h \
		../../qtbase_bb10/include/QtCore/qatomic_bfin.h \
		../../qtbase_bb10/include/QtCore/qatomic_ia64.h \
		../../qtbase_bb10/include/QtCore/qatomic_mips.h \
		../../qtbase_bb10/include/QtCore/qatomic_s390.h \
		../../qtbase_bb10/include/QtCore/qatomic_sh4a.h \
		../../qtbase_bb10/include/QtCore/qatomic_sparc.h \
		../../qtbase_bb10/include/QtCore/qatomic_x86.h \
		../../qtbase_bb10/include/QtCore/qatomic_cxx11.h \
		../../qtbase_bb10/include/QtCore/qatomic_gcc.h \
		../../qtbase_bb10/include/QtCore/qatomic_unix.h \
		../../qtbase_bb10/include/QtCore/qbytearray.h \
		../../qtbase_bb10/include/QtCore/qrefcount.h \
		../../qtbase_bb10/include/QtCore/qnamespace.h \
		../../qtbase_bb10/include/QtCore/qarraydata.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/strings.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/x86/string.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/string_chk.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdlib.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/malloc.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_pack64.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/alloca.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/_packpop.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/wait.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/signal.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/sys/siginfo.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdarg.h \
		../../qtbase_bb10/include/QtCore/qstring.h \
		../../qtbase_bb10/include/QtCore/qchar.h \
		../../qtbase_bb10/include/QtCore/qstringbuilder.h \
		../../qtbase_bb10/include/QtCore/qvarlengtharray.h \
		../../qtbase_bb10/include/QtCore/qcontainerfwd.h \
		../../qtbase_bb10/include/QtCore/qalgorithms.h \
		../../qtbase_bb10/include/QtCore/qisenum.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs.h \
		../../qtbase_bb10/include/QtCore/qobjectdefs_impl.h \
		../../qtbase_bb10/include/QtGui/qopengl.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/GLES2/gl2.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/GLES2/gl2platform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/KHR/khrplatform.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdint.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/inttypes.h \
		../../qtbase_bb10/include/QtGui/qopengles2ext.h \
		../../qtbase_bb10/include/QtCore/qt_windows.h \
		../../qtbase_bb10/include/QtGui/qopenglext.h \
		../../qtbase_bb10/include/QtGui/qwindow.h \
		../../qtbase_bb10/include/QtCore/QObject \
		../../qtbase_bb10/include/QtCore/qobject.h \
		../../qtbase_bb10/include/QtCore/qlist.h \
		../../qtbase_bb10/include/QtCore/qiterator.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/limits.h \
		../../qtbase_bb10/include/QtCore/qcoreevent.h \
		../../qtbase_bb10/include/QtCore/qscopedpointer.h \
		../../qtbase_bb10/include/QtCore/qobject_impl.h \
		../../qtbase_bb10/include/QtCore/QEvent \
		../../qtbase_bb10/include/QtCore/QMargins \
		../../qtbase_bb10/include/QtCore/qmargins.h \
		../../qtbase_bb10/include/QtCore/QRect \
		../../qtbase_bb10/include/QtCore/qrect.h \
		../../qtbase_bb10/include/QtCore/qsize.h \
		../../qtbase_bb10/include/QtCore/qpoint.h \
		../../qtbase_bb10/include/QtGui/qsurface.h \
		../../qtbase_bb10/include/QtGui/qsurfaceformat.h \
		../../qtbase_bb10/include/QtGui/qwindowdefs.h \
		../../qtbase_bb10/include/QtGui/qwindowdefs_win.h \
		../../qtbase_bb10/include/QtGui/qicon.h \
		../../qtbase_bb10/include/QtGui/qpixmap.h \
		../../qtbase_bb10/include/QtGui/qpaintdevice.h \
		../../qtbase_bb10/include/QtGui/qcolor.h \
		../../qtbase_bb10/include/QtGui/qrgb.h \
		../../qtbase_bb10/include/QtCore/qstringlist.h \
		../../qtbase_bb10/include/QtCore/qdatastream.h \
		../../qtbase_bb10/include/QtCore/qiodevice.h \
		../../qtbase_bb10/include/QtCore/qpair.h \
		../../qtbase_bb10/include/QtCore/qregexp.h \
		../../qtbase_bb10/include/QtCore/qstringmatcher.h \
		../../qtbase_bb10/include/QtCore/qsharedpointer.h \
		../../qtbase_bb10/include/QtCore/qshareddata.h \
		../../qtbase_bb10/include/QtCore/qsharedpointer_impl.h \
		../../qtbase_bb10/include/QtCore/qhash.h \
		../../qtbase_bb10/include/QtGui/qimage.h \
		../../qtbase_bb10/include/QtGui/qtransform.h \
		../../qtbase_bb10/include/QtGui/qmatrix.h \
		../../qtbase_bb10/include/QtGui/qpolygon.h \
		../../qtbase_bb10/include/QtCore/qvector.h \
		../../qtbase_bb10/include/QtGui/qregion.h \
		../../qtbase_bb10/include/QtCore/qline.h \
		../../qtbase_bb10/include/QtGui/qpainterpath.h \
		../../qtbase_bb10/include/QtGui/qcursor.h \
		../../qtbase_bb10/include/QtGui/qevent.h \
		../../qtbase_bb10/include/QtGui/qkeysequence.h \
		../../qtbase_bb10/include/QtCore/qvariant.h \
		../../qtbase_bb10/include/QtCore/qmap.h \
		../../qtbase_bb10/include/QtCore/qdebug.h \
		../../qtbase_bb10/include/QtCore/qtextstream.h \
		../../qtbase_bb10/include/QtCore/qlocale.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio.h \
		../../bbndkGold/target_10_0_9_1673/qnx6/usr/include/stdio_chk.h \
		../../qtbase_bb10/include/QtCore/qset.h \
		../../qtbase_bb10/include/QtCore/qcontiguouscache.h \
		../../qtbase_bb10/include/QtCore/qurl.h \
		../../qtbase_bb10/include/QtCore/qurlquery.h \
		../../qtbase_bb10/include/QtCore/qfile.h \
		../../qtbase_bb10/include/QtCore/qfiledevice.h \
		../../qtbase_bb10/include/QtGui/qvector2d.h \
		../../qtbase_bb10/include/QtGui/qtouchdevice.h \
		../../qtbase_bb10/include/QtQml/qqmldebug.h \
		../../qtbase_bb10/include/QtQml/qtqmlglobal.h \
		../../qtbase_bb10/include/QtCore/QCoreApplication \
		../../qtbase_bb10/include/QtCore/qcoreapplication.h \
		../../qtbase_bb10/include/QtCore/qeventloop.h \
		../../qtbase_bb10/include/QtCore/QDir \
		../../qtbase_bb10/include/QtCore/qdir.h \
		../../qtbase_bb10/include/QtCore/qfileinfo.h \
		../../qtbase_bb10/include/QtQml/QQmlEngine \
		../../qtbase_bb10/include/QtQml/qqmlengine.h \
		../../qtbase_bb10/include/QtQml/qjsengine.h \
		../../qtbase_bb10/include/QtQml/qjsvalue.h \
		../../qtbase_bb10/include/QtQml/qqmlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtquick2applicationviewer.o qtquick2applicationviewer/qtquick2applicationviewer.cpp

moc_qtquick2applicationviewer.o: moc_qtquick2applicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtquick2applicationviewer.o moc_qtquick2applicationviewer.cpp

moc_mediabackend.o: moc_mediabackend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mediabackend.o moc_mediabackend.cpp

####### Install

install_itemfolder_01: first FORCE
	@test -d $(INSTALL_ROOT)/opt/cassette/qml || $(MKDIR) $(INSTALL_ROOT)/opt/cassette/qml 
	-$(INSTALL_DIR) /Users/mehdi/QtProjects/cassette/qml/cassette $(INSTALL_ROOT)/opt/cassette/qml/

uninstall_itemfolder_01: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/cassette/qml/cassette
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/cassette/qml/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/cassette/bin || $(MKDIR) $(INSTALL_ROOT)/opt/cassette/bin 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/cassette/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/cassette/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/cassette/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

